<template><div class="profile" v-loading="loading"><header><div><div style="display:flex;align-items:center;gap:14px"><UserAvatar :size="54"/><div><span class="eyebrow">YOUR WORKSPACE</span><h1>{{ profile.nickname || "个人中心" }}</h1></div></div><p>管理账号资料，了解你的工具使用情况。</p></div><ElButton @click="load">刷新统计</ElButton></header><div class="metrics"><ElCard v-for="item in metrics" :key="item.label"><span>{{ item.label }}</span><strong>{{ item.value }}</strong></ElCard></div><ElTabs model-value="environment"><ElTabPane label="环境变量" name="environment"><AccountEnvironment/></ElTabPane><ElTabPane label="工具使用统计"><p class="hint">按每个工具版本统计已创建的任务，包含网页及本人 API Key 调用；幂等重试不重复计数。最近7天为滚动168小时。</p><ElTable :data="stats.tools" empty-text="尚未使用工具，去工具库运行一次吧"><ElTableColumn prop="title" label="工具"/><ElTableColumn prop="version" label="版本"/><ElTableColumn prop="total" label="使用次数"/><ElTableColumn prop="succeeded" label="成功"/><ElTableColumn prop="failed" label="失败 / 超时"/><ElTableColumn prop="pending" label="待完成"/><ElTableColumn prop="canceled" label="已取消"/><ElTableColumn label="最近使用" min-width="180"><template #default="{row}">{{ new Date(row.last_used_at).toLocaleString() }}</template></ElTableColumn></ElTable></ElTabPane><ElTabPane label="个人资料"><ElForm class="account-form" label-position="top"><ElFormItem label="登录账号"><ElInput :model-value="profile.username" disabled/></ElFormItem><ElFormItem label="昵称"><ElInput v-model="profile.nickname" maxlength="50"/></ElFormItem><ElFormItem label="注册邮箱"><ElInput v-model="profile.email" maxlength="254" disabled/><small>{{ profile.email_verified ? '邮箱已验证' : '历史账号未验证邮箱' }}</small></ElFormItem><ElFormItem label="个人简介"><ElInput v-model="profile.bio" type="textarea" :rows="4" maxlength="500" show-word-limit/></ElFormItem><ElButton type="primary" :loading="saving" @click="save">保存资料</ElButton></ElForm></ElTabPane><ElTabPane label="账号安全"><ElForm class="account-form" label-position="top"><p class="hint">修改密码后所有设备需重新登录。API Key 独立管理，不受密码修改影响。</p><ElFormItem label="当前密码"><ElInput v-model="password.current_password" type="password" show-password autocomplete="current-password"/></ElFormItem><ElFormItem label="新密码（至少12位）"><ElInput v-model="password.password" type="password" show-password autocomplete="new-password"/></ElFormItem><ElFormItem label="确认新密码"><ElInput v-model="confirmation" type="password" show-password autocomplete="new-password"/></ElFormItem><ElButton type="primary" :loading="saving" @click="change">修改密码并重新登录</ElButton></ElForm></ElTabPane></ElTabs></div></template>
<script setup lang="ts">
import {ref,reactive,computed,onMounted} from 'vue'
import {ElMessage} from 'element-plus'
import request from '@/utils/http'
import AccountEnvironment from '../components/AccountEnvironment.vue'
import UserAvatar from '../components/UserAvatar.vue'
import {useUserStore} from '@/store/modules/user'
defineOptions({name:'Profile'})
const user=useUserStore(),loading=ref(false),saving=ref(false),profile=ref<any>({}),stats=ref<any>({summary:{},tools:[],last_seven_days:0}),confirmation=ref(''),password=reactive({current_password:'',password:''})
const metrics=computed(()=>[{label:'累计使用',value:stats.value.summary.total||0},{label:'执行成功',value:stats.value.summary.succeeded||0},{label:'失败 / 超时',value:stats.value.summary.failed||0},{label:'最近7天',value:stats.value.last_seven_days||0}])
async function load(){loading.value=true;try{[profile.value,stats.value]=await Promise.all([request.get({url:'/core/system/user'}),request.get({url:'/core/account/stats'})])}finally{loading.value=false}}
async function save(){saving.value=true;try{const {nickname,email,bio}=profile.value;const info=await request.request<Api.Auth.UserInfo>({url:'/core/system/user',method:'PATCH',data:{nickname,email,bio}});user.setUserInfo(info);ElMessage.success('资料已保存')}finally{saving.value=false}}
async function change(){if(password.password!==confirmation.value){ElMessage.warning('两次密码不一致');return}saving.value=true;try{await request.post({url:'/core/account/password',data:password});password.password='';password.current_password='';confirmation.value='';ElMessage.success('密码已更新，请重新登录');user.logOut()}finally{saving.value=false}}
onMounted(load)
</script><style scoped>header{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}h1{font-size:26px;font-weight:700}header p,.hint{margin:12px 0 24px;color:var(--el-text-color-secondary);line-height:1.8}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:18px;margin-bottom:28px}.metrics span{color:var(--el-text-color-secondary)}.metrics strong{display:block;font-size:32px;margin-top:12px}.account-form{max-width:560px;padding-top:18px}@media(max-width:700px){.metrics{grid-template-columns:repeat(2,1fr)}}</style>

<style scoped>.profile>header{padding:30px 32px;background:linear-gradient(115deg,#edf0ff 0%,#f6f8ff 65%,#eaf7f4 100%);border:1px solid #e4e9f6;border-radius:20px;color:#27324d}.eyebrow{font-size:10px;letter-spacing:2px;color:#7180a6;display:block;margin-bottom:7px}.profile>header p{margin:18px 0 0;color:#6a7690}.metrics{gap:14px}.metrics :deep(.el-card){border-radius:16px;box-shadow:none;border-color:var(--el-border-color-lighter)}.metrics strong{font-size:30px;letter-spacing:-1px}.metrics span{font-size:12px}.profile>:deep(.el-tabs){padding:12px 28px 28px;background:var(--el-bg-color);border:1px solid var(--el-border-color-lighter);border-radius:18px}.profile :deep(.el-tabs__item){height:58px;font-size:14px}.profile :deep(.el-tabs__nav-wrap:after){height:1px}.profile :deep(.el-tab-pane){padding-top:20px}.account-form{padding:12px 0}.profile :deep(.el-input__wrapper){min-height:42px;border-radius:9px}@media(max-width:600px){.profile>header{padding:22px 18px}.profile>:deep(.el-tabs){padding:4px 16px 22px}.profile>header>.el-button{display:none}}</style>
