<template><div class="register"><ElCard><h1>创建 ToolDeck 账号</h1><p>开始使用工具，保存属于你的执行记录。</p><ElForm label-position="top" @submit.prevent="submit"><ElFormItem label="昵称"><ElInput v-model="form.nickname" maxlength="50"/></ElFormItem><ElFormItem label="邮箱账号" required><ElInput v-model="form.email" type="email" autocomplete="email" placeholder="注册后使用此邮箱登录"/></ElFormItem><ElFormItem label="邮箱验证码" required><ElInput v-model="form.code" maxlength="6" inputmode="numeric" autocomplete="one-time-code" placeholder="6位验证码"><template #append><ElButton :disabled="remaining>0" :loading="sending" @click="sendCode">{{ remaining>0 ? `${remaining}秒后重发` : '发送验证码' }}</ElButton></template></ElInput></ElFormItem><ElFormItem label="密码"><ElInput v-model="form.password" type="password" show-password autocomplete="new-password" placeholder="至少12位"/></ElFormItem><ElFormItem label="确认密码"><ElInput v-model="confirm" type="password" show-password autocomplete="new-password" @keyup.enter="submit"/></ElFormItem><ElButton type="primary" :loading="busy" @click="submit">注册账号</ElButton><ElButton link @click="router.push('/auth/login')">返回登录</ElButton></ElForm></ElCard></div></template>
<script setup lang="ts">
import {ref,reactive,onBeforeUnmount} from 'vue'
import {useRouter} from 'vue-router'
import {ElMessage} from 'element-plus'
import request from '@/utils/http'
const router=useRouter(),busy=ref(false),confirm=ref(''),form=reactive({nickname:'',password:'',email:'',code:''})
const sending=ref(false),remaining=ref(0)
let timer:ReturnType<typeof setInterval>|undefined
async function sendCode(){if(sending.value||remaining.value>0)return;if(!form.email.trim()){ElMessage.warning('请填写邮箱');return}sending.value=true;try{const result=await request.post<{retry_after:number}>({url:'/core/register/email-code',data:{email:form.email}});remaining.value=result.retry_after;ElMessage.success('验证码已发送，请查收邮箱');timer=setInterval(()=>{remaining.value--;if(remaining.value<=0)clearInterval(timer)},1000)}finally{sending.value=false}}
onBeforeUnmount(()=>clearInterval(timer))
async function submit(){if(busy.value)return;if(form.password!==confirm.value){ElMessage.warning('两次密码不一致');return}busy.value=true;try{await request.post({url:'/core/register',data:form});ElMessage.success('注册成功，请登录');await router.push('/auth/login')}finally{busy.value=false}}
</script><style scoped>.register{min-height:100vh;display:grid;place-items:center;background:#f4f7fc;padding:24px}.el-card{width:min(480px,100%);padding:24px;border-radius:18px}h1{font-size:26px;font-weight:700}p{margin:12px 0 24px;color:var(--el-text-color-secondary)}</style>
