<template><section class="env-panel"><div class="env-heading"><div><h2>统一环境变量</h2><p>常用的 API 密钥和服务地址，配置一次，在你的工具中复用。</p></div><ElButton type="primary" @click="edit()">＋ 添加变量</ElButton></div><div class="priority"><span>配置优先级</span><b>工具个人配置</b><i>→</i><b>账号统一配置</b><i>→</i><b>作者共享配置</b></div><p class="note">仅向工具已声明的同名变量注入，网页与 API 调用均适用。变量值加密保存，保存后不再显示。</p><ElInput v-model="search" placeholder="搜索变量名称" clearable class="search"/><div v-loading="loading"><div v-for="name in filtered" :key="name" class="env-row"><div class="env-icon">{ }</div><div class="env-info"><code>{{name}}</code><small>•••••••••••• · 已加密保存</small></div><ElButton text @click="edit(name)">更新值</ElButton><ElButton text type="danger" @click="remove(name)">删除</ElButton></div><ElEmpty v-if="!filtered.length" :description="search?'没有匹配的变量':'添加第一个变量，让常用配置随账号同行'" :image-size="90"/></div><ElDialog v-model="open" :title="editing?'更新环境变量':'添加环境变量'" width="min(480px, 92vw)" @closed="value=''"><ElForm label-position="top"><ElFormItem label="变量名称"><ElInput v-model="name" :disabled="editing" placeholder="例如 OPENAI_API_KEY" maxlength="64"/></ElFormItem><ElFormItem label="变量值"><ElInput v-model="value" type="password" show-password placeholder="输入新的值"/></ElFormItem></ElForm><template #footer><ElButton @click="open=false">取消</ElButton><ElButton type="primary" :loading="saving" @click="save">加密保存</ElButton></template></ElDialog></section></template>
<script setup lang="ts">
import {ref,computed,onMounted} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {td} from '@/api/tooldeck'
const names=ref<string[]>([]),search=ref(''),loading=ref(false),saving=ref(false),open=ref(false),editing=ref(false),name=ref(''),value=ref('')
const filtered=computed(()=>names.value.filter(n=>n.toLowerCase().includes(search.value.toLowerCase())))
async function load(){loading.value=true;try{names.value=await td.list('environment')}finally{loading.value=false}}
function edit(n=''){name.value=n;value.value='';editing.value=!!n;open.value=true}
async function save(){if(!/^[A-Z][A-Z0-9_]{0,63}$/.test(name.value)){ElMessage.warning('名称使用大写字母、数字和下划线，并以字母开头');return}if(!value.value){ElMessage.warning('请输入变量值');return}saving.value=true;try{await td.save('environment',{values:{[name.value]:value.value}});open.value=false;value.value='';await load();ElMessage.success('已加密保存')}finally{saving.value=false}}
async function remove(n:string){try{await ElMessageBox.confirm(`删除 ${n} 后，使用此配置的工具可能需要重新配置。`,'删除变量',{type:'warning'})}catch{return}await td.save('environment',{delete:[n]});await load()}
onMounted(load)
</script>
<style scoped>.env-heading{display:flex;justify-content:space-between;align-items:center;gap:20px}.env-heading h2{font-size:20px;font-weight:650;margin:0 0 10px}.env-heading p,.note{color:var(--el-text-color-secondary);line-height:1.8;font-size:13px}.priority{display:flex;align-items:center;flex-wrap:wrap;gap:14px;padding:18px 20px;background:var(--el-fill-color-light);border-radius:12px;margin:24px 0 12px;font-size:12px}.priority span,.priority i{color:var(--el-text-color-secondary);font-style:normal}.priority b{font-weight:500}.search{max-width:320px;margin:20px 0}.env-row{display:flex;align-items:center;gap:14px;padding:20px 4px;border-bottom:1px solid var(--el-border-color-lighter)}.env-icon{width:42px;height:42px;display:grid;place-items:center;border-radius:12px;background:#eef2ff;color:#5269ef;font:600 17px monospace}.env-info{flex:1;min-width:0}.env-info code{overflow-wrap:anywhere;font-size:14px}.env-info small{display:block;color:var(--el-text-color-secondary);margin-top:7px;font-size:11px}@media(max-width:600px){.env-heading{align-items:flex-start;flex-direction:column}.env-row{gap:6px}.env-icon{display:none}}</style>
