<template><section><h2>工具环境变量</h2><p class="hint">按工具集中管理，配置与工具详情同步。不同工具即使变量名相同，也完全隔离；同一作者同一工具的不同版本复用个人值。</p><ElSelect v-model="selected" filterable placeholder="选择要配置的工具" style="width:100%;margin:16px 0" :loading="loading"><ElOption v-for="t in tools" :key="t.id" :value="t.id" :label="`${t.manifest.title} · ${t.manifest.name}`"/></ElSelect><ToolEnvironment v-if="selected" :key="selected+revision" :tool-id="selected"/><ElEmpty v-else :description="tools.length?'选择工具后会展示作者声明的变量':'当前没有需要配置环境变量的工具'" :image-size="70"/><ElCollapse v-if="legacy.length" class="legacy"><ElCollapseItem title="旧账号级变量（已停用自动注入）"><p class="hint">旧值仍加密保留。选择已声明对应变量的工具，再手动导入；不会覆盖工具已有值，也不会同步给其他工具。</p><ElCheckboxGroup v-model="importKeys"><ElCheckbox v-for="name in legacy" :key="name" :value="name">{{name}}</ElCheckbox></ElCheckboxGroup><ElButton :disabled="!selected||!importKeys.length" :loading="importing" @click="migrate">导入到当前工具</ElButton></ElCollapseItem></ElCollapse></section></template>
<script setup lang="ts">
import {ref,onMounted} from 'vue'
import {ElMessage} from 'element-plus'
import {td,type Tool} from '@/api/tooldeck'
import ToolEnvironment from './ToolEnvironment.vue'
const tools=ref<Tool[]>([]),selected=ref(''),loading=ref(false),legacy=ref<string[]>([]),importKeys=ref<string[]>([]),revision=ref(0),importing=ref(false)
onMounted(async()=>{loading.value=true;try{const [all,old]=await Promise.all([td.tools(),td.list('environment')]);const seen=new Set<string>();tools.value=all.filter(t=>{const key=`${t.owner}:${t.manifest.name}`;if(seen.has(key))return false;seen.add(key);return !!t.manifest.env?.length});legacy.value=old;if(tools.value.length)selected.value=tools.value[0].id}finally{loading.value=false}})
async function migrate(){importing.value=true;try{await td.save('environment',{copy_to_tool:selected.value,import_keys:importKeys.value});importKeys.value=[];revision.value++;ElMessage.success('已导入当前工具，其他工具不受影响')}finally{importing.value=false}}
</script><style scoped>h2{font-size:20px;font-weight:650}.hint{font-size:13px;color:var(--el-text-color-secondary);line-height:1.9;margin:12px 0}.legacy{margin-top:26px}.el-button{margin-top:12px}</style>
