<template><div><ElAlert title="配置值加密保存，不会写入代码包。留空表示保留已保存的值；删除值请使用清除按钮。" type="info" :closable="false"/><ElForm label-position="top" style="margin-top:20px"><ElFormItem v-if="author" label="当前编辑的配置"><ElRadioGroup v-model="scope" @change="load"><ElRadio value="personal">我的个人配置</ElRadio><ElRadio value="shared">提供给使用者的共享配置</ElRadio></ElRadioGroup></ElFormItem><ElFormItem label="作者的默认凭证策略"><ElRadioGroup v-model="mode" :disabled="!author"><ElRadio value="developer">允许使用作者共享配置</ElRadio><ElRadio value="user">必须使用个人配置</ElRadio></ElRadioGroup></ElFormItem><p v-if="mode==='developer'">优先使用工具个人配置，其次使用个人中心的统一环境变量，最后使用作者共享值；共享凭证可能消耗作者额度。</p><p v-else>网页和本人 API Key 调用共用自己的配置；工具未单独配置时，使用个人中心的同名统一变量。</p><div v-for="(field,index) in fields" :key="index" class="env-row"><ElInput v-model="field.name" :disabled="!author" placeholder="变量名，例如 IMAGE_API_KEY"/><ElInput v-if="author" v-model="field.description" placeholder="用途说明" maxlength="300"/><p v-else>{{ field.description }}</p><div v-if="author"><ElCheckbox v-model="field.required">必填</ElCheckbox><ElCheckbox v-model="field.sensitive">敏感值</ElCheckbox><ElButton text type="danger" @click="fields.splice(index,1)">移除定义</ElButton></div><template v-if="true"><ElInput v-model="field.newValue" :type="field.sensitive?'password':'text'" :show-password="field.sensitive" :placeholder="field.configured?'已配置；输入新值以替换':'请输入配置值'" autocomplete="off"/><ElButton v-if="field.configured" text type="danger" @click="clear(field)">{{ field.clear?'已标记清除':'清除已保存值' }}</ElButton></template><ElTag v-else>由开发者配置</ElTag></div><ElEmpty v-if="!fields.length" description="此工具尚未声明环境变量" :image-size="50"/><ElButton v-if="author" @click="fields.push({name:'',description:'',required:false,sensitive:true,newValue:''})">＋ 添加变量</ElButton><ElButton v-if="true" type="primary" :loading="saving" @click="save">保存配置</ElButton></ElForm></div></template>
<script setup lang="ts">
import {ref,onMounted} from 'vue'
import {td} from '@/api/tooldeck'
import request from '@/utils/http'
import {ElMessage} from 'element-plus'
const props=defineProps<{toolId:string}>()
const scope=ref('personal')
const mode=ref('developer'),author=ref(false),fields=ref<any[]>([]),saving=ref(false)
async function load(){const data=await request.get<any>({url:`/v1/tools/${props.toolId}/environment?scope=${scope.value}`});mode.value=data.mode;author.value=data.author;fields.value=data.fields.map((f:any)=>({...f,newValue:'',clear:false}))}
function clear(field:any){field.clear=!field.clear;field.newValue=''}
async function save(){saving.value=true;try{const values:Record<string,string>={};const deleted:string[]=[];for(const f of fields.value){if(f.newValue!=='')values[f.name]=f.newValue;else if(f.clear)deleted.push(f.name)}const data:any={values,delete:deleted};if(author.value){data.mode=mode.value;data.fields=fields.value.map(({name,description,required,sensitive})=>({name,description,required,sensitive}))}await td.save(`tools/${props.toolId}/environment?scope=${scope.value}`,data);ElMessage.success('环境变量已保存');await load()}finally{saving.value=false}}
onMounted(load)
</script><style scoped>.env-row{padding:16px;background:var(--el-fill-color-light);border-radius:10px;margin:16px 0;display:grid;gap:10px}p{margin:10px 0;color:var(--el-text-color-secondary)}</style>
