<template><div><h1>工具审核</h1><ElCard class="setting"><div class="row"><div><h2>公开工具上传审核</h2><p>开启后，新的公开工具须审核通过才能被其他登录用户看到。私有工具不需要审核。</p><small>关闭仅影响后续上传，不会自动通过已有待审核工具。</small></div><ElSwitch :model-value="required" :loading="saving" @change="toggle"/></div></ElCard><div class="row"><ElSelect v-model="filter" style="width:180px"><ElOption label="待审核" value="pending"/><ElOption label="已通过" value="approved"/><ElOption label="未通过" value="rejected"/><ElOption label="全部公开工具" value="all"/></ElSelect><ElButton @click="load">刷新</ElButton></div><ElTable :data="filtered" v-loading="loading"><ElTableColumn label="工具"><template #default="{row}">{{ row.manifest.title }}<small style="display:block">{{ row.manifest.name }} · {{ row.manifest.version }}</small></template></ElTableColumn><ElTableColumn prop="owner" label="上传者"/><ElTableColumn label="状态"><template #default="{row}">{{ labels[row.review_status||'approved'] }}</template></ElTableColumn><ElTableColumn label="操作" width="300"><template #default="{row}"><ElButton link @click="selected=row;detail=true">查看配置</ElButton><ElButton link @click="download(row as Tool)">下载代码</ElButton><ElButton :disabled="!!row.build_status&&row.build_status!=='ready'" link type="success" @click="review(row as Tool,'approved')">通过</ElButton><ElButton link type="danger" @click="review(row as Tool,'rejected')">拒绝</ElButton></template></ElTableColumn></ElTable><ElDialog v-model="detail" title="工具配置" width="min(800px,95vw)"><pre>{{ JSON.stringify(selected,null,2) }}</pre></ElDialog></div></template>
<script setup lang="ts">
import {ref,computed,onMounted} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {td,type Tool} from '@/api/tooldeck'
import {useUserStore} from '@/store/modules/user'
import request from '@/utils/http'
defineOptions({name:'Review'})
const required=ref(true),saving=ref(false),loading=ref(false),items=ref<Tool[]>([]),filter=ref('pending'),selected=ref<Tool>(),detail=ref(false)
const labels:Record<string,string>={pending:'待审核',approved:'已通过',rejected:'未通过'}
const filtered=computed(()=>items.value.filter(t=>filter.value==='all'||(t.review_status||'approved')===filter.value))
async function load(){loading.value=true;try{const [settings,tools]=await Promise.all([request.get<{required:boolean}>({url:'/v1/review-settings'}),td.list('reviews')]);required.value=settings.required;items.value=tools}finally{loading.value=false}}
async function toggle(value:any){saving.value=true;try{await td.save('review-settings',{required:!!value});required.value=!!value;ElMessage.success('审核设置已保存')}finally{saving.value=false}}
async function review(tool:Tool,status:string){const {value}=await ElMessageBox.prompt(status==='approved'?'确认公开此工具？可填写审核备注。':'请输入拒绝原因，上传者可见。','审核工具',{inputValidator:v=>v.length<=500&&(status==='approved'||v.trim().length>0)||'拒绝原因必填，最多500字'});await td.save('reviews/'+tool.id,{status,note:value||''});ElMessage.success('审核结果已保存');await load()}
async function download(tool:Tool){const response=await fetch(`${import.meta.env.VITE_API_URL}/v1/reviews/${tool.id}/package`,{headers:{Authorization:`Bearer ${useUserStore().accessToken}`}});if(!response.ok){ElMessage.error('下载失败');return}const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=tool.manifest.name+'.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
onMounted(load)
</script><style scoped>h1{font-size:28px;font-weight:700;margin-bottom:22px}h2{font-weight:600}.setting{margin-bottom:24px}.row{display:flex;align-items:center;justify-content:space-between;gap:20px}p{margin:10px 0;color:var(--el-text-color-secondary)}small{color:var(--el-text-color-secondary)}pre{white-space:pre-wrap;overflow-wrap:anywhere}.el-table{margin-top:20px}</style>

